import { Helmet } from 'react-helmet-async';
import { useLocation } from 'react-router-dom';
import { SITE_URL } from '@/components/shared/StructuredData';

const SITE_NAME = 'Pro-Tech IT Consulting';
// 1200x630 social share image (generated by scripts/generate-og-image.mjs).
const DEFAULT_OG_IMAGE = `${SITE_URL}/og-image.png`;

function SEO({ title, description, canonicalUrl, ogImage }) {
  const { pathname } = useLocation();
  const fullTitle = title.includes('Pro-Tech') ? title : `${title} — ${SITE_NAME}`;
  // Build a canonical/OG URL from the current route unless one is passed explicitly.
  // GitHub Pages serves directory routes with a trailing slash (/about -> 301 ->
  // /about/), so we use the trailing-slash form to match the actual 200 URL rather
  // than point the canonical at a redirecting URL.
  const canonical =
    canonicalUrl || `${SITE_URL}${pathname === '/' ? '/' : pathname.replace(/\/+$/, '') + '/'}`;
  const image = ogImage || DEFAULT_OG_IMAGE;

  return (
    <Helmet>
      <title>{fullTitle}</title>
      {description && <meta name="description" content={description} />}
      <link rel="canonical" href={canonical} />

      {/* Open Graph */}
      <meta property="og:site_name" content={SITE_NAME} />
      <meta property="og:title" content={fullTitle} />
      {description && <meta property="og:description" content={description} />}
      <meta property="og:image" content={image} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:alt" content={`${SITE_NAME} — ${fullTitle}`} />
      <meta property="og:url" content={canonical} />
      <meta property="og:type" content="website" />

      {/* Twitter Card */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={fullTitle} />
      {description && <meta name="twitter:description" content={description} />}
      <meta name="twitter:image" content={image} />
    </Helmet>
  );
}

export default SEO;
