import {
  LuNetwork,
  LuCable,
  LuWifi,
  LuPhone,
  LuShield,
  LuHeadset,
  LuCloud,
  LuClipboardList,
  LuHeart,
  LuLandmark,
  LuGraduationCap,
  LuBuilding,
  LuShoppingCart,
  LuFactory,
  LuCheck,
  LuArrowRight,
  LuMenu,
  LuX,
  LuChevronDown,
  LuChevronRight,
  LuMapPin,
  LuMail,
  LuClock,
  LuLinkedin,
  LuTwitter,
  LuExternalLink,
  LuTarget,
  LuEye,
  LuUsers,
  LuAward,
  LuSettings,
  LuZap,
  LuShieldCheck,
  LuServer,
  LuMonitor,
  LuLock,
  LuGlobe,
  LuGauge,
  LuRefreshCw,
  LuSmartphone,
  LuLayoutDashboard,
  LuClipboardCheck,
  LuTag,
  LuRadar,
  LuVideo,
  LuMessageSquare,
  LuPhoneForwarded,
  LuLaptop,
  LuCamera,
  LuDoorOpen,
  LuBell,
  LuHardDrive,
  LuScanFace,
  LuCloudUpload,
  LuLayers,
  LuDollarSign,
  LuContainer,
  LuKanban,
  LuTriangleAlert,
  LuFileText,
  LuCircleCheck,
  LuMonitorCheck,
  LuWrench,
  LuDatabase,
  LuUser,
  LuHouse,
} from 'react-icons/lu';

const iconMap = {
  LuNetwork,
  LuCable,
  LuWifi,
  LuPhone,
  LuShield,
  LuHeadset,
  LuCloud,
  LuClipboardList,
  LuHeart,
  LuLandmark,
  LuGraduationCap,
  LuBuilding,
  LuShoppingCart,
  LuFactory,
  LuCheck,
  LuArrowRight,
  LuMenu,
  LuX,
  LuChevronDown,
  LuChevronRight,
  LuMapPin,
  LuMail,
  LuClock,
  LuLinkedin,
  LuTwitter,
  LuExternalLink,
  LuTarget,
  LuEye,
  LuUsers,
  LuAward,
  LuSettings,
  LuZap,
  LuShieldCheck,
  LuServer,
  LuMonitor,
  LuLock,
  LuGlobe,
  LuGauge,
  LuRefreshCw,
  LuSmartphone,
  LuLayoutDashboard,
  LuClipboardCheck,
  LuTag,
  LuRadar,
  LuVideo,
  LuMessageSquare,
  LuPhoneForwarded,
  LuLaptop,
  LuCamera,
  LuDoorOpen,
  LuBell,
  LuHardDrive,
  LuScanFace,
  LuCloudUpload,
  LuLayers,
  LuDollarSign,
  LuContainer,
  LuKanban,
  LuTriangleAlert,
  LuAlertTriangle: LuTriangleAlert,
  LuFileText,
  LuCircleCheck,
  LuCheckCircle: LuCircleCheck,
  LuMonitorCheck,
  LuWrench,
  LuDatabase,
  LuUser,
  LuHouse,
  LuHome: LuHouse,
};

const sizeMap = {
  sm: 'h-5 w-5',
  md: 'h-6 w-6',
  lg: 'h-10 w-10',
  xl: 'h-12 w-12',
};

function Icon({ name, size = 'md', className = '' }) {
  const IconComponent = iconMap[name];
  if (!IconComponent) return null;

  return <IconComponent className={`${sizeMap[size] || sizeMap.md} ${className}`.trim()} />;
}

export default Icon;
